### ISSUE TITLE
Playback continues in background

### ISSUE THREAD

**Issue by FahadLive** [Ranger-NF/Blackhole-Linux#3]
**Describe the bug**
Playback continues even after closing the app

**Steps To Reproduce**
1. Open the app
2. Play any song
3. Close the app

**Expected behavior**
Playback of the song should stop

**Device Details (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu 22.04
 - App Version: 0.1

**Comment by BrightDV** [comment]
I found a workaround which is not very convenient but, in case of…
There is a [small script](https://github.com/hoyon/mpv-mpris/releases/download/1.0/mpris.so) called [mpv-mpris](https://github.com/hoyon/mpv-mpris) which you can add to mpv's config scripts (`.config/mpv/scripts`).
It adds the current file played by mpv to the media center's notification, so you can pause the song when it is in background.

However, the metadata is still missing, I will see if I can change it to show at least the name and not some id (edit: doesn't seem doable sadly).

edit 2: might be helpful: https://github.com/ProjectAnni/mpris_service/

**Comment by FahadLive** [comment]
https://github.com/ProjectAnni/mpris_service looks promising
