### ISSUE TITLE
Can't play another song when one is already playing

### ISSUE THREAD

**Issue by BrightDV** [Ranger-NF/Blackhole-Linux#4]
**Describe the bug**
When playing one song ~~on **YouTube Music**~~, you can't play another one after searching.

**Steps To Reproduce**
*Just found that it is same for all the sections.*

1. Search for some music in any section ~~on YouTube *Music*~~
4. Play a song
5. Click on another song from the results.

**Expected behavior**
To play the second songs too.

**App Logs:**

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Write failed (OS Error: Relais brisé (pipe), errno = 32), address = /tmp/MPV_Dart.sock, port = 0

> #0      _NativeSocket.write (dart:io-patch/socket_patch.dart:1201:34)
#1      _RawSocket.write (dart:io-patch/socket_patch.dart:1944:15)
#2      _Socket._write (dart:io-patch/socket_patch.dart:2387:18)
#3      _SocketStreamConsumer.write (dart:io-patch/socket_patch.dart:2134:26)
#4      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2108:11)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#9      _StreamController._add (dart:async/stream_controller.dart:648:7)
#10     _StreamController.add (dart:async/stream_controller.dart:596:5)
#11     _StreamSinkImpl.add (dart:io/io_sink.dart:136:17)
#12     _IOSinkImpl.write (dart:io/io_sink.dart:269:5)
#13     _Socket.write (dart:io-patch/socket_patch.dart:2224:36)

#14     IPCInterface.send
#15     IPCInterface.getProperty
#16     MPVPlayer.getProperty
#17     MPVPlayer.getDuration
#18     JustAudioMPVPlayer.update
#19     new JustAudioMPVPlayer.<anonymous closure>
> #20     EventEmitter.emit

#21     MPVPlayer._messageHandler
#22     MPVPlayer.start.<anonymous closure>
> #23     EventEmitter.emit

#24     IPCInterface.dataHandler.<anonymous closure>
> #25     List.forEach (dart:core-patch/growable_array.dart:416:8)

#26     IPCInterface.dataHandler
#27     IPCInterface.connect.<anonymous closure>

> #28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#31     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#32     _StreamController._add (dart:async/stream_controller.dart:648:7)
#33     _StreamController.add (dart:async/stream_controller.dart:596:5)
#34     _Socket._onData (dart:io-patch/socket_patch.dart:2355:41)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#39     _StreamController._add (dart:async/stream_controller.dart:648:7)
#40     _StreamController.add (dart:async/stream_controller.dart:596:5)
#41     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1877:33)
#42     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1334:14)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
</details>

**Comment by FahadLive** [comment]
I was unable to reproduce the issue in the new version
