### ISSUE TITLE
Not able to play songs but songs can be downloaded

### ISSUE THREAD

**Issue by SiCKmand** [Ranger-NF/Blackhole-Linux#5]
I am not able to listen to Songs but I can download Songs using Blackhole for Linux

**Comment by FahadLive** [comment]
Have you installed `mpv` library on your machine? The app depends on it for playback...

**Comment by SiCKmand** [comment]
yes I tried after installing mpv library 
Both libmpv and mpv on my machine and it's still not working, Any suggestions?

**Comment by FahadLive** [comment]
Huh, That's weird. Its the only dependency. Can you double check the installation using `mpv --version` and see if it gives an output.

If the problem persists, let me know. I might look into it when I'm free 🙂
